name: Node.js CI

on:
  pull_request:
    branches: [ "main", "QA", "Dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./express-gen-ts

    - name: Wait for MongoDB to be ready
      run: |
        sudo apt-get install -y wait-for-it
        wait-for-it localhost:27017 --timeout=30 --strict -- echo "MongoDB is ready"

    - name: Run build
      run: npm run build --if-present
      working-directory: ./express-gen-ts

    - name: Run tests
      env:
        MONGO_URI: mongodb://localhost:27017/testdb
      run: npm run test:no-reloading
      working-directory: ./express-gen-ts
